# Generated by Django 5.2.8 on 2025-11-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('poster_image', models.CharField(blank=True, max_length=500, null=True)),
                ('genres', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterboxd_scraper.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterboxd_scraper.user')),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
    ]
