# Generated by Django 5.2.8 on 2026-01-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterboxd_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film_id',
            new_name='letterboxd_id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='link',
        ),
        migrations.AddField(
            model_name='film',
            name='letterboxd_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
